// <auto-generated />
using System;
using DatabaseLayer.ApplicationContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseLayer.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260121095140_RemoveVehicleTypeFromCraneOilChangeLog")]
    partial class RemoveVehicleTypeFromCraneOilChangeLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessLayer.Model.CraneOilChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Change_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Changed_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Crane_VehicleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Meter_Reading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NextDue_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Oil_Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Oil_Qty")
                        .HasColumnType("int");

                    b.Property<string>("Oil_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Unit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Vehicle_TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Crane_VehicleId");

                    b.HasIndex("Vehicle_TypeId");

                    b.ToTable("craneOilChangeLogs");
                });

            modelBuilder.Entity("BusinessLayer.Model.CraneOtherExpenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expense_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Expense_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paid_To")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payment_Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vehicle_TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Vehicle_TypeId");

                    b.ToTable("craneOtherExpenses");
                });

            modelBuilder.Entity("BusinessLayer.Model.Crane_Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Capacity_Tons")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Import_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Import_From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacture_Year")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Max_Lifting_Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purchase_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vehicle_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vehicle_No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vehicle_TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Vehicle_TypeId");

                    b.ToTable("tbl_CraneVehicle");
                });

            modelBuilder.Entity("BusinessLayer.Model.Fuel_Expenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fuel_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fuel_Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Fuel_Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fuel_Station")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Odometer_Reading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Payment_Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Receipt_No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Vehicle_TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Vehicle_TypeId");

                    b.ToTable("tbl_FuelExpenses");
                });

            modelBuilder.Entity("BusinessLayer.Model.Loan_Installment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount_Paid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Installment_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Paid_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payment_Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receipt_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Vehicle_LoanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Vehicle_LoanId");

                    b.ToTable("tbl_LoanInstallment");
                });

            modelBuilder.Entity("BusinessLayer.Model.Service_Master", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Performed_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Service_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Service_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Vehicle_TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Vehicle_TypeId");

                    b.ToTable("tbl_ServiceMaster");
                });

            modelBuilder.Entity("BusinessLayer.Model.Service_Parts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Parts_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Service_MasterId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Unit_Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Service_MasterId");

                    b.ToTable("tbl_ServiceParts");
                });

            modelBuilder.Entity("BusinessLayer.Model.Vehicle_Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact_Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Crane_VehicleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Interest_Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Loan_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Loan_Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monthly_Installment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Term_Month")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Vehicle_TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Crane_VehicleId");

                    b.HasIndex("Vehicle_TypeId");

                    b.ToTable("tbl_VehicleLoan");
                });

            modelBuilder.Entity("BusinessLayer.Model.Vehicle_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_Vehicles");
                });

            modelBuilder.Entity("BusinessLayer.Model.CraneOilChangeLog", b =>
                {
                    b.HasOne("BusinessLayer.Model.Crane_Vehicle", "Crane_Vehicle")
                        .WithMany("CraneOilChanges")
                        .HasForeignKey("Crane_VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.Vehicle_Type", null)
                        .WithMany("CraneOilChangesLog")
                        .HasForeignKey("Vehicle_TypeId");

                    b.Navigation("Crane_Vehicle");
                });

            modelBuilder.Entity("BusinessLayer.Model.CraneOtherExpenses", b =>
                {
                    b.HasOne("BusinessLayer.Model.Vehicle_Type", "VehicleType")
                        .WithMany("craneOtherExpenses")
                        .HasForeignKey("Vehicle_TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("BusinessLayer.Model.Crane_Vehicle", b =>
                {
                    b.HasOne("BusinessLayer.Model.Vehicle_Type", "Vehicle_Type")
                        .WithMany("Crane_Vehicles")
                        .HasForeignKey("Vehicle_TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle_Type");
                });

            modelBuilder.Entity("BusinessLayer.Model.Fuel_Expenses", b =>
                {
                    b.HasOne("BusinessLayer.Model.Vehicle_Type", "Vehicle_Type")
                        .WithMany("Fuel_Expenses")
                        .HasForeignKey("Vehicle_TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle_Type");
                });

            modelBuilder.Entity("BusinessLayer.Model.Loan_Installment", b =>
                {
                    b.HasOne("BusinessLayer.Model.Vehicle_Loan", "Vehicle_Loan")
                        .WithMany("loan_Installments")
                        .HasForeignKey("Vehicle_LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle_Loan");
                });

            modelBuilder.Entity("BusinessLayer.Model.Service_Master", b =>
                {
                    b.HasOne("BusinessLayer.Model.Vehicle_Type", "VehicleType")
                        .WithMany("Service_Masters")
                        .HasForeignKey("Vehicle_TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("BusinessLayer.Model.Service_Parts", b =>
                {
                    b.HasOne("BusinessLayer.Model.Service_Master", "Service_Master")
                        .WithMany("service_Parts")
                        .HasForeignKey("Service_MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service_Master");
                });

            modelBuilder.Entity("BusinessLayer.Model.Vehicle_Loan", b =>
                {
                    b.HasOne("BusinessLayer.Model.Crane_Vehicle", "Crane_Vehicle")
                        .WithMany()
                        .HasForeignKey("Crane_VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Model.Vehicle_Type", null)
                        .WithMany("Vehicle_Loans")
                        .HasForeignKey("Vehicle_TypeId");

                    b.Navigation("Crane_Vehicle");
                });

            modelBuilder.Entity("BusinessLayer.Model.Crane_Vehicle", b =>
                {
                    b.Navigation("CraneOilChanges");
                });

            modelBuilder.Entity("BusinessLayer.Model.Service_Master", b =>
                {
                    b.Navigation("service_Parts");
                });

            modelBuilder.Entity("BusinessLayer.Model.Vehicle_Loan", b =>
                {
                    b.Navigation("loan_Installments");
                });

            modelBuilder.Entity("BusinessLayer.Model.Vehicle_Type", b =>
                {
                    b.Navigation("CraneOilChangesLog");

                    b.Navigation("Crane_Vehicles");

                    b.Navigation("Fuel_Expenses");

                    b.Navigation("Service_Masters");

                    b.Navigation("Vehicle_Loans");

                    b.Navigation("craneOtherExpenses");
                });
#pragma warning restore 612, 618
        }
    }
}
